### ISSUE TITLE
Criar página personalizada para apresentar os parlamentares do partido

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/prj#1]
Disponibilizar informações de parlamentares do partido, contendo: 

1 - Nome Completo
2 - Endereço e telefone do gabinete
3 - Prestação de contas do mandato(pode ser um embed de planília ou anexo)
4 - Linque para declarações do TRE
5 - Equipe do Mandato
6 - Descrição aberta (histórico, comissões que faz parte, etc)
7 - Projetos de lei apresentados 
8 - Formulário de cadastro para receber informações do mandato

**Comment by eduardozulian** [comment]
É essa a ordem de prioridade das informações?

**Comment by eduardozulian** [comment]
E se _Declarações do TRE_, _Prestação de contas do mandato_ e _Equipe_ estivessem todos embaixo de um item **Transparência**?

**Comment by jpmehl** [comment]
Boa proposta.
Em 31/08/2015 09:38, "Eduardo Zulian" notifications@github.com escreveu:

**Comment by eduardozulian** [comment]
Subi uma ideia em https://campanhacompleta.github.io/prj/parlamentar.html. Avaliem!

**Comment by eduardozulian** [comment]
Tem uma coisa que eu não gosto nesse wireframe: a barra lateral. E se usássemos um [esquema assim](http://proparty.axiomthemes.com/team/alberto-hoffman/) ou [assim](http://chimpgroup.com/wp-demo/westand/westand-politics/teams/anna-warson/)?

**Comment by jpmehl** [comment]
Achei a parada de poder colocar "depoimentos" bem legal. 
E uma coisa que não tem, mas que poderiamos prever para frente, é a possibildiade de conectar as Leis feitas pelo parlamentar e as notícias publicadas sobre ele. 
Neste momento, acho que uma solução seria nas notícias criarmos uma categoria(ou até uma tag) com o nome do Parlamentar, dai a gente só colocaria o linque de atalho.

**Comment by eduardozulian** [comment]
Acho que para o momento não usamos nada, @jpmehl, não dessa maneira (referenciando tags com nome do parlamentar, só se fosse em forma de editoria mesmo). Pode ser uma melhoria pra frente, certeza, mas talvez a gente precise responder antes a questão #7. :smile:
