### ISSUE TITLE
TV Partido 

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/prj#3]
Página interna que possibilite a integração de vídeos do Youtube ou Vimeo, com possibilidade de inserção de Set list dos vídeos

**Comment by eduardozulian** [comment]
Não é melhor que isso seja linkado para o provedor de vídeos do partido mesmo? Ou que eles sejam simplesmente posts com o `post format` vídeo?

**Comment by jpmehl** [comment]
Então, tem o lance do Post format vídeo que organiza os vídeos, mas o recurso do youtube de montar a set list faz diferença, acho que é só um embed, mas que acho interessante termos.

**Comment by eduardozulian** [comment]
Se a página vai apenas conter uma playlist do YouTube, ela vai ser igual a todas as outras páginas. Não é preciso prever isso especificamente agora.

**Comment by jpmehl** [comment]
Acredito que podemos resolver assim para a primeira entrega, mas pensando
que os vídeos podem ser de mais de um canal(do partido e dos
parlamentares), seria importante termos na nossa mira uma solução mais
robusta e interna a plataforma.
Talvez já tenha algum plugin ou solução pronta para o WP...

Em 31 de agosto de 2015 09:14, Eduardo Zulian notifications@github.com
escreveu:

> Se a página vai apenas conter uma playlist do YouTube, ela vai ser igual a
> todas as outras páginas. Não é preciso prever isso especificamente agora.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/campanhacompleta/prj/issues/3#issuecomment-136354782.

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9221-1909

**Comment by eduardozulian** [comment]
Então vamos fechar isso aqui por enquanto, já que é relacionado a um plugin e não ao tema especificamente, ok?

**Comment by jpmehl** [comment]
OK, em paralelo a gente dá uma pesquisada nos possíveis plugins.

Em 1 de setembro de 2015 16:40, Eduardo Zulian notifications@github.com
escreveu:

> Então vamos fechar isso aqui por enquanto, já que é relacionado a um
> plugin e não ao tema especificamente, ok?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/campanhacompleta/prj/issues/3#issuecomment-136837124.

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9221-1909
