### ISSUE TITLE
Widget menu footer

### ISSUE THREAD

**Issue by jacsonp** [campanhacompleta/prj#8]
Sem hover no menu do footer

**Comment by eduardozulian** [comment]
Tem certeza que é nesse projeto o problema? :smile:

**Comment by jacsonp** [comment]
sim, mas descrevi e errado, quis dizer hover quase imperceptível. Em monitor ruim, nem da para ver mesmo

**Comment by jacsonp** [comment]
campanhacompleta/publico#49
